name: New Source Proposal
description: Submit a new data source for evaluation by the DMOG team
title: "[New Source] Add <SOURCE NAME>"
labels: ["source-review", "triage"]
assignees: [eKathleenCarter]

body:
  - type: markdown
    attributes:
      value: |
        ## Instructions
        Please fill out as much information as possible about the proposed source. This form supports evaluation based on FAIR principles (Findable, Accessible, Interoperable, Reusable).
        You do not need to complete every field — enter what you know and link to additional information where possible.

  ####################################
  # FINDABLE
  ####################################

  - type: input
    id: source-name
    attributes:
      label: Source Name
      description: Full name and acronym, if applicable
      placeholder: e.g., Comparative Toxicogenomics Database (CTD)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short summary of the source’s purpose and content
      placeholder: e.g., CTD provides curated data on chemical–gene and chemical–disease interactions.

  - type: input
    id: maintainer
    attributes:
      label: Maintainer
      description: Individual or organization responsible for the source
      placeholder: e.g., NC State University

  - type: dropdown
    id: proponent
    attributes:
      label: Proponent
      description: How was this source brought to our attention?
      options:
        - Collaborator
        - Manuscript
        - Conference Presentation
        - Other
        
  - type: input
    id: other-proponent
    attributes:
      label: Other Proponent or Name of Collaborator (if selected)
      placeholder: e.g., “Translator Listserv discussion”, "John Smith"

  ####################################
  # ACCESSIBLE
  ####################################

  - type: input
    id: access-link
    attributes:
      label: Access Mechanism
      description: Link to website, download page, or API documentation
      placeholder: https://...

  - type: input
    id: license
    attributes:
      label: License
      description: License name and any use restrictions (e.g., CC-BY 4.0, CC0)
      placeholder: e.g., CC-BY 4.0
  - type: markdown
    attributes:
      value: |
        > ⚠️ **Note**: ROBOKOP currently does not ingest proprietary sources, require payment, or impose restrictive access terms.

  ####################################
  # INTEROPERABLE
  ####################################

  - type: checkboxes
    id: bio-levels
    attributes:
      label: Biological Levels Covered
      description: Select all levels of biological content that apply
      options:
        - label: Small Molecule / Drug
        - label: Protein / Gene / Nucleic Acid
        - label: Organelle / Cell
        - label: Tissue / Organ
        - label: Mechanism of Action
        - label: Biological Process / Pathway
        - label: Disease / Phenotype
        - label: Environmental Exposure
        - label: Other (please specify below)

  - type: input
    id: other-bio-level
    attributes:
      label: Other Biological Level (if selected)
      placeholder: e.g., Cell Line, Pathogen, etc.

  - type: textarea
    id: impact
    attributes:
      label: Proposed Impact
      description: What benefit would the inclusion of this source provide?
      placeholder: e.g., This dataset would expand coverage of metabolite–gene interactions in cancer biology.

  ####################################
  # REUSABLE
  ####################################

  - type: input
    id: use-case
    attributes:
      label: Use-case Link (if applicable)
      description: If this source supports a specific ROBOKOP use case, please link to the exact issue in the Use-Cases repo and briefly describe the connection.
      placeholder: e.g., https://github.com/RobokopU24/Use-Cases/issues/1 — expands coverage for rare disease phenotype mapping
